### PR TITLE
Organisation name change

### PR DESCRIPTION
**Pull request by martafullen**
Organisation name changed to comply with the project page

### CODE REVIEW

**Comment by netomi** [comment]
If you assign a project lead as reviewer and get approval, you can auto-merge that yourself by following the instructions that will be added as comment.

**Comment by aorzelskiGH** [comment]
Approved

**Comment by aorzelskiGH** [comment]
Approved

**Review by aorzelskiGH — APPROVED** [review]

**Comment by netomi** [comment]
In case you missed that, you can automerge yourself now by adding `/otterdog merge` as comment. Project-leads can do that as well. There is also a status page at https://otterdog.eclipse.org/admin/pullrequests to see what PRs are open and if they are eligible for automerge in case you are not sure.

**Review by netomi — APPROVED** [review]

**Pull request merged**
